name: Generate Snake Animation
on:
  schedule:
    - cron: "0 0 * * *" # Runs daily
  push:
    branches:
      - main # Adjust to your default branch
  workflow_dispatch: # Allows manual trigger
jobs:
  generate-snake:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Platane/snk@v3
        with:
          github_user_name: Devnath03
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
      - uses: actions/upload-artifact@v4
        with:
          name: snake-animation
          path: dist/
      - name: Push to output branch
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git checkout -B output
          git add dist/
          git commit -m "Update snake animation"
          git push origin output --force
